### PR TITLE
Avoid invalid escape sequences.

### PR DESCRIPTION
**Pull request by Danack**
They drive my OCD wild.

### CODE REVIEW

**Comment by staabm** [comment]
OCD?

**Comment by Danack** [comment]
[OCD](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder) - I know the code already was working, but I see invalid escape sequences in a string and my left eye starts twitching.

**Comment by bwoebi** [comment]
I still don't know why that is an invalid escape sequence…
It just is a backslash. It's only an escape sequence if followed by a suited character... But meh…

**Comment by kelunik** [comment]
@bwoebi No, it's invalid if followed by non-suited character. Otherwise, new characters like `\u` will be a BC break.

**Pull request merged**
