### PR TITLE
Implement Future::then()

### PR DESCRIPTION
**Pull request by trowski**
For feedback on using `then` instead of `apply`, as more people are familiar with the `then` API from JS.

### CODE REVIEW

**Comment by xpader** [comment]
Why hasn't this been merged into V3 yet? Any concerns?

**Comment by kelunik** [comment]
Because we're unsure whether we want to. `then()` brings specific expectations that we might not want to support, because it's simply not needed with fibers, e.g. returning another `Future` from inside the `then()` callback.

**Comment by xpader** [comment]
I think we just need a simple `then()` at this time, not full Promise/A+ implement, like just `apply()` rename to `then()`, because name `apply` is ugly..

**Comment by kelunik** [comment]
Do you have any name suggestions apart from then()? If it's not Promises/A+, I'd like to avoid that name.

**Comment by xpader** [comment]
May be `done`? Still think `then` is the best name

**Comment by kelunik** [comment]
Another name I had in mind was `map` like Java's optional.

**Comment by xpader** [comment]
Future is a thing that can set a success and fail callback to, I think the method name must be related to success-failure, or resolved-rejected state. Name `apply` and `map` looks like have no help for understanding success or failure state.

**Comment by kelunik** [comment]
`then` doesn't tell anything about success or failure either.

**Comment by xpader** [comment]
`then` does not tell about sucess or failure because `then` has two parameters that include success and failure, and `then` is Promise/A+ 😓..

**Comment by xpader** [comment]
It seems that I cannot convince you to change the name of apply().
I hope that the V3 API can stabilize as soon as possible so that I can develop the next version of my framework (It's alreay adapter the old V3).

**Comment by kelunik** [comment]
Yeah, we've decided to avoid `then()` for now, as there's no good reason to have it other than JS having it.

**Comment by xpader** [comment]
Cry.

**Comment by trowski** [comment]
map is used for similar functions on placeholders in other languages. Don't get hung up on the name "then" just because JS uses it. Most guides recommend against using the second parameter (e.g., https://exploringjs.com/es6/ch_promises.html#sec_common-promise-chaining-mistakes) and use another catch call instead, so why repeat the same API mistakes here?

**Pull request closed without merging**
