### PR TITLE
Add strict_types + clean type-covered docblocks

### PR DESCRIPTION
**Pull request by TomasVotruba**
Brought to you by [EasyCodingStandard](https://github.com/Symplify/EasyCodingStandard)

### CODE REVIEW

**Comment by PeeHaa** [comment]
Why did you remove the `void` return types?

**Comment by PeeHaa** [comment]
Also I have a feeling you are in for a fight when trying to add strict types.

**Comment by kelunik** [comment]
Moving to strict types would be a BC break and we explicitly decided not to go with strict types.

**Comment by TomasVotruba** [comment]
> Also I have a feeling you are in for a fight when trying to add strict types.

What do you mean by that?

> kelunik

This would be targetting next major release of course.

**Comment by kelunik** [comment]
The next major release is not planned, yet, and likely to be released in the far future. It doesn't make sense to have code-style PRs for a future major release, yet.

Which kind of additional feedback would you like to have?

**Comment by PeeHaa** [comment]
Void type is only available as of 7.1... This library support 7.

Even if this library would have supported 7.1+ you just removed the doc block return type and didn't actually add the return type. So basically you just removed information.

**Comment by TomasVotruba** [comment]
Usually people add these when bumping to PHP 7 to decrease upgrading for end users. I thought you'd be open to this. It looked like it was forgotten.

Well, the doc cleanup.

**Comment by PeeHaa** [comment]
> > Also I have a feeling you are in for a fight when trying to add strict types.

> What do you mean by that?

Because I have had some discussion about this some while ago with the maintainers and their stance has been: nope, don't we don't do strict types.

**Comment by kelunik** [comment]
Usually the return documentation blocks should have a description added instead of being removed. And strict types have been discussed and it was explicitly decided to avoid using them due to callbacks.

**Comment by TomasVotruba** [comment]
@PeeHaa Ah, I didn't know that. Could you share a link?

**Comment by TomasVotruba** [comment]
> @kelunik  Usually the return documentation blocks should have a description added instead of being removed.

Could explain why?

> decided to avoid using them due to callbacks.

I have no idea what this means. Could you explain in code please?

**Comment by PeeHaa** [comment]
> decided to avoid using them due to callbacks.

Because the strict types declaration of callback are not defined where you think they are.

**Comment by TomasVotruba** [comment]
> Because the strict types declaration of callback are not defined where you think they are.

Code would be more helpful, I don't use callback much so I don't know what you mean.

**Pull request closed without merging**
