### PR TITLE
Add Iterator\collect

### PR DESCRIPTION
**Pull request by kelunik**
Another possible name would be `toArray`, not sure which one is better.

### CODE REVIEW

**Comment by bwoebi** [comment]
I think `toArray` is favorable here as it's more explicit. And is also alluding to the well known `iterator_to_array()`.

**Comment by trowski** [comment]
I also prefer `toArray`. `collect` is elegant, but not self-documenting like `toArray`.

**Comment by Sevavietl** [comment]
@trowski Hi.

Will this PR be merged soon? Need this function in multiple projects, so do not want to copy-paste my own implementation.

Thank you in advance.

**Comment by kelunik** [comment]
@Sevavietl now. ;-)

**Comment by Sevavietl** [comment]
@kelunik Thank you for the quick response.

Do you know when the next release will be? So I can require it instead of dev-master.

**Comment by kelunik** [comment]
Soon.™

I planned today, not sure whether I'll get to that.

**Comment by Sevavietl** [comment]
@kelunik Thank you. No biggie.

By the way, I have created [some custom matchers](https://github.com/OWOX/PhpSpecAmp) for phpspec, so as soon as this function will be released will use it for spec-testing of `Producers` and `Iterators`.

Thank you again for the great library.

**Comment by kelunik** [comment]
@Sevavietl Thanks!

**Pull request merged**
