### PR TITLE
Alternative approach to adding Loop::now()

### PR DESCRIPTION
**Pull request by trowski**
This PR (hopefully) adds `Loop::now()` in a BC way.

### CODE REVIEW

**Comment by bwoebi** [comment]
Looks good, but aren't we going to use uv_now() with UvDriver?

**Comment by trowski** [comment]
@bwoebi Yep, I forgot about `uv_now()`. Pushed a new commit that uses it.

**Comment by kelunik** [comment]
I just noticed that this breaks decorating driver implementations, as they have the inherited now() implementation then, but never call tick().

**Comment by kelunik** [comment]
Closing in favor of #208.

**Pull request closed without merging**
